#Service DB
apiVersion: v1
kind: Service
metadata:
  name: bluechat-db-prod
  namespace: bluechat-prod
spec:
  type: ClusterIP
  selector:
    app: bluechat-db-prod
  ports:
    - name: db-port
      protocol: TCP
      port: 3306
      targetPort: 3306

---

#Deploy DB
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy-prod
  namespace: bluechat-prod
spec:
  replicas: 1
  template:
    metadata:
        name: bluechat-db-prod
        labels:
          app: bluechat-db-prod
    spec:
      containers:
      - name: bluechat-db
        image: jonfarias/bluechat-db:1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        #volumeMounts:
        #  - mountPath: "/var/lib/mysql"
        #    name: db-disk
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
          name: bluechat-secret-prod
      #volumes:
       # - name: db-disk
        #  persistentVolumeClaim:
        #    claimName: db-k8s-pvc
  selector:
    matchLabels:
      app: bluechat-db-prod

---

#Service Bluechat
apiVersion: v1
kind: Service
metadata:
  name: bluechat-prod
  namespace: bluechat-prod
spec:
  type: ClusterIP
  selector:
    app: bluechat-prod
  ports:
  - name: http
    port: 80
    targetPort: 5000

---
#Deploy Bluechat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluechat-deploy
  namespace: bluechat-prod
spec:
  replicas: 1
  template:
    metadata:
        name: bluechat-prod
        labels:
          app: bluechat-prod
    spec:
      initContainers:
        - name: check-mysql
          image: busybox:1.31.1
          command: ['sh', '-c', 'until nslookup db.bluechat-prod.svc.cluster.local; do echo waiting for mysql; sleep 2; done;'] 
      containers:
      - name: bluechat-container
        image: jonfarias/bluechat-web:$TAG
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
          name: bluechat-secret-prod
  selector:
    matchLabels:
      app: bluechat-prod