#Service Bluechat
apiVersion: v1
kind: Service
metadata:
  name: bluechat
spec:
  type: NodePort
  selector:
    app: bluechat
  ports:
  - name: http
    port: 80
    targetPort: 5000
    nodePort: 30000

---
#Deploy Bluechat
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluechat-deploy
spec:
  replicas: 1
  template:
    metadata:
        name: bluechat
        labels:
          app: bluechat
    spec:
      initContainers:
        - name: check-mysql
          image: busybox:1.31.1
          command: ['sh', '-c', 'until nslookup db.default.svc.cluster.local; do echo waiting for mysql; sleep 2; done;'] 
      containers:
      - name: bluechat-container
        image: jonfarias/bluechat-web:$TAG
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: MYSQL_DATABASE
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-database
        - name: MYSQL_USER
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-password
        - name: MYSQL_HOST
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-host
        - name: MYSQL_PORT
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: mysql-port
        - name: SECRET_KEY
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: secret-key
        - name: SESSION_TYPE
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: session-type    
        - name: FLASK_ENV
          valueFrom:
              secretKeyRef:
                name: bluechat-secret
                key: flask-env    
  selector:
    matchLabels:
      app: bluechat