version: 2.1
orbs:
  python: circleci/python@1.2
  slack: circleci/slack@4.6.0

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:
  Test: 
    working_directory: ~/BlueChat-CI/
    docker:
      - image: cimg/python:3.8
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout:
          path: ~/BlueChat-CI
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv bluechat
            . bluechat/bin/activate
            pip install --no-cache-dir -r chat/requirements.txt
      - run:
          name: Run Tests
          command: |
            . bluechat/bin/activate
            pytest chat/test/ -v
      - persist_to_workspace:
          root: .
          paths:
            - ./manifests
      - notify_slack_error
      - notify_slack_pass
  Build and Publish:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/bluechat-web:$TAG chat/.
          echo $DOCKER_PASSWD | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/bluechat-web:$TAG
          docker tag $DOCKER_USER/bluechat-web:$TAG $DOCKER_USER/bluechat-web:latest
          docker push $DOCKER_USER/bluechat-web:latest
      - notify_slack_error
      - notify_slack_pass
  GenerateYAML-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/jonfarias/BlueChat-CD /tmp/BlueChat-CD
          cd /tmp/BlueChat-CD
          cp -r /tmp/workspace/manifests .
          sed -i 's/\(bluechat-web\)\(.*\)/\1:'$TAG'/' ./manifests/bluechat-prod/bluechat-deploy.yml
          git config credential.helper 'cache --timeout=120'
          git config user.email "jonathan.developer10@gmail.com"
          git config user.name "BlueChat-CircleCI"
          git add .
          git commit -m "Update via CircleCI - BUILD_NUM = $TAG"
          git branch -M main
          git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/jonfarias/BlueChat-CD.git main
      - notify_slack_error
      - notify_slack_pass

  request-approval:
    docker:
      - image: cimg/base:stable
    steps:
      - slack/notify:
          event: hold
          template: basic_on_hold_1

  GenerateYAML-prod:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/jonfarias/BlueChat-CD /tmp/BlueChat-CD
          cd /tmp/BlueChat-CD
          cp -r /tmp/workspace/manifests .
          sed -i 's/\(bluechat-web\)\(.*\)/\1:'$TAG'/' ./manifests/bluechat-prod/bluechat-deploy.yml
          git config credential.helper 'cache --timeout=120'
          git config user.email "jonathan.developer10@gmail.com"
          git config user.name "BlueChat-CircleCI"
          git add .
          git commit -m "Update via CircleCI - BUILD_NUM = $TAG"
          git branch -M main
          git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/jonfarias/BlueChat-CD.git main


workflows:
  version: 2
  CI:
    jobs:
      - Test:       
          filters:
            branches:
              only: main
          context:
            - Slack
      - Build and Publish:
          requires:
            - Test
          filters:
            branches:
              only: main
          context:
            - Slack
      - GenerateYAML-dev:
          requires:
            - Build and Publish
          filters:
            branches:
              only: main
          context:
            - Slack