version: 2.1
orbs:
  python: circleci/python@1.2
jobs:
  Test: 
    working_directory: ~/BlueChat-CI/
    docker:
      - image: cimg/python:3.8
        environment:
          FLASK_CONFIG: testing
    steps:
      - checkout:
          path: ~/BlueChat-CI
      - run:
          name: Setup VirtualEnv
          command: |
            virtualenv bluechat
            . bluechat/bin/activate
            pip install --no-cache-dir -r app/requirements.txt
      #- run:
      #    name: Run Tests
      #    command: |
      #      . helloworld/bin/activate
      #      python test_hello_world.py
      - persist_to_workspace:
          root: .
          paths:
            - ./bluechat-deploy.yml
  Build and Publish:
    docker:
      - image: cimg/python:3.8
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWD
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
          docker_layer_caching: true
      - run: |
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t $DOCKER_USER/bluechat-web:$TAG app/.
          echo $DOCKER_PASSWD | docker login -u $DOCKER_USER --password-stdin
          docker push $DOCKER_USER/bluechat-web:$TAG
          docker tag $DOCKER_USER/bluechat-web:$TAG $DOCKER_USER/bluechat-web:latest
          docker push $DOCKER_USER/bluechat-web:latest
  GenerateYAML:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run : |
          TAG=0.1.$CIRCLE_PREVIOUS_BUILD_NUM
          git clone https://github.com/jonfarias/BlueChat-CD /tmp/BlueChat-CD
          cd /tmp/BlueChat-CD
          cp /tmp/workspace/bluechat-deploy.yml .
          sed -i 's/\(bluechat-web\)\(.*\)/\1:'$TAG'/' ./bluechat-deploy.yml
          git config credential.helper 'cache --timeout=120'
          git config user.email "jonathan.developer10@gmail.com"
          git config user.name "BlueChat-CircleCI"
          git add .
          git commit -m "Update via CircleCI - BUILD_NUM = $TAG"
          git branch -M main
          # Push quietly
          git push -q https://$GITHUB_PERSONAL_TOKEN@github.com/jonfarias/BlueChat-CD.git main



workflows:
  version: 2
  CI:
    jobs:
      - Test:       
          filters:
            branches:
              only: main
      - Build and Publish:
          requires:
            - Test
          filters:
            branches:
              only: main
      - GenerateYAML:
          requires:
            - Build and Publish
          filters:
            branches:
              only: main